---
- hosts: servers
  gather_facts: false

  vars:

  tasks:
  ### Get Uptime post system boot into Original VG vg00
  - name: Check the uptime post reboot
    shell: uptime
    register: UPTIME_POST_ALTCHECK

  - debug: msg={{ UPTIME_POST_ALTCHECK.stdout }}
